### ISSUE TITLE
Permissions not working with latest sponge versions

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#15] opened 2017-03-19 10:12 UTC
Hello,

I've had this plugin on my server for a while and recently (probably because I updated sponge) the permissions are not working anymore. Could this be something on playershopsrpg's side? Because I doubt its something with luckyperms seeing as all other permissions still seem to work.

Also when players use a negative value it seems they can get free money from it.

Thanks for the plugin

Cheers!
- Whazaaaaa

**Comment by Zerthick** [comment] 2017-03-19 20:43
That's bizarre, what version of sponge are you running?

**Comment by Whazaaaaa** [comment] 2017-03-19 20:49
1.10.2-2254-5.2.0-BETA-2234
Is what I'm currently running on the servers that have this problem with permissions.

I also have other servers where it still works they are running this:
spongeforge-1.10.2-2221-5.1.0-BETA-2156

Wish I could be of more help but I just noticed this. even when I give the permissions playershopsrpg.* still some things arent working properly. Then I can do /select but am unable to actually select the area.

**Comment by Whazaaaaa** [comment] 2017-03-19 20:52
Perhaps it has to do with the luckperms version. Ill check this aswell.

**Comment by Whazaaaaa** [comment] 2017-03-19 21:04
Just tried latest luckperms latest spongeforge and playershops sadly permissions are not working :(

**Comment by Zerthick** [comment] 2017-03-20 02:00
Are you getting a "You don't have permission!" message or are the commands just not working?

**Comment by Whazaaaaa** [comment] 2017-03-20 06:10
a no permission message. when I give myself "*": true as permissions it works.

**Comment by Zerthick** [comment] 2017-03-20 15:13
Hmmm, that's strange, could you give me some more examples of actions that seem to break?  Nothing in PlayerShopsRPG should break between minor version updates of Sponge, which leads me to believe that this is a luckperms issue. Could you try reverting to the version of luckperms you are using on the servers that are currently working and seeing if the problem persists?  That would determine if it is luckperms or Sponge itself.

**Comment by Whazaaaaa** [comment] 2017-03-21 19:09
Okay so I tried a way older luckperms that I was using where its still working but seems that its either something with spongeforge that is messing with it.

**Comment by Zerthick** [comment] 2017-03-22 01:32
Hmmm, and you haven't added any additional plugins that could be interfering with it either?

**Comment by Whazaaaaa** [comment] 2017-03-22 06:40
OKay did a fresh install on my pc.
LuckPerms-Sponge-3.0.51
Nucleus-0.26.1-1.10.2-S5.1-plugin
PlayerShopsRPG-v1.1.0
spongeforge-1.10.2-2254-5.2.0-BETA-2231
is all I have now. yet still not working.

These are the permissions I gave.
`- playershopsrpg.command.{select,create,destroy,browse}:
    value: true
- playershopsrpg.command.balance.{deposit,withdraw}:
    value: true
- playershopsrpg.command.item.{buy,sell,add,remove,set,create,destroy}:
    value: true
- playershopsrpg.command.manager.{add,remove}:
    value: true
- playershopsrpg.command.set.{name,owner,type,price,rent}:
    value: true`

**Comment by Zerthick** [comment] 2017-03-22 16:03
Ah, that's because in v1.1 of PlayerShopsRPG I changed the commands permissions to include an "s" in command to match the convention of other sponge plugins so `playershopsrpg.command.select` would change to `playershopsrpg.command`**s**`.select`. You can see a full updated list of permissions [here](https://github.com/Zerthick/PlayerShopsRPG/wiki/Permissions).

**Comment by Whazaaaaa** [comment] 2017-03-22 17:38
well now I just feel stupid sorry for the trouble xD

**Comment by Whazaaaaa** [comment] 2017-04-05 08:42
Okay so completely different error but the title still applies so I thought why not use this one.
So i've recently updated to the newest SpongeForge 2264 and it seems that after updating to that the playershops stopped working.
I have a pastebin https://pastebin.com/pwwwCKyw that shows the error logs in my fml-server-latest.log

Am I doing something wrong again or is this actually something with playershops not liking the new spongeforge?

Thanks!

**Comment by Whazaaaaa** [comment] 2017-04-08 09:42
Sp i've tried using the latest spongeforge on a different version and its working just fine. So now im at a loss what is happening here. I dont know what to get from those crashlogs. Anything someone can find?

**Comment by Zerthick** [comment] 2017-04-10 18:30
When you  say a different version, do you mean a different version of PlayerShopsRPG?

Part 1 is related to reading in the different shop types from the config file, did you edit that file when doing the upgrade?

Part 2 is related to storing the shop items so that they can be retrieve and recreated later.

Both of these services are provided by Sponge which is why it's conceivable that they may break, however they should not break so long as the major version number remains the same. The latest release of PlayerShopsRPG [v1.1.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v1.1.0) was testing against version 5 of the API, so any 5.x build of sponge should be compatible with it, however the bleeding edge API 6.x versions of sponge may not work.

Also, do be careful you aren't using PlayerShopsRPG v1.1.1, as that was a backport intended to only be used on API 4.x builds of sponge.

**Comment by Whazaaaaa** [comment] 2017-04-10 20:07
With different version I ment a plain new spongeforge server without any mods. I have not edited the files form playershops so they should be find I dont know. I've added my files if you'd like to look at them.


[shops.zip](https://github.com/Zerthick/PlayerShopsRPG/files/911319/shops.zip)

**Comment by Zerthick** [comment] 2017-04-10 21:21
What is the different version?

**Comment by Whazaaaaa** [comment] 2017-04-11 05:37
Currently running:
spongeforge-1.10.2-2254-5.2.0-BETA-2264
PlayerShopsRPG-v1.1.0

I've also tried testing if the same would happen on a clean server with:
spongeforge-1.10.2-2254-5.2.0-BETA-2264
and 
spongeforge-1.10.2-2254-5.2.0-BETA-2272
PlayerShopsRPG-v1.1.0
But on the clean servers this problem didnt occur again, making me think its something inside the shop config/ shop file atm.

**Comment by Zerthick** [comment] 2017-06-23 03:12
So I think this is a duplicate of #25, the issue here appears to be that you have modded items in your shops, but no longer have those mods installed, I'll close this issue in favor of continuing the discussion in the newer one.

**Closed by Zerthick** 2017-06-23 03:12 UTC
