### ISSUE TITLE
Plugin broke with weird item in shop

### ISSUE THREAD

**Issue by Whazaaaaa** [Zerthick/PlayerShopsRPG#25] opened 2017-06-20 16:06 UTC
Hai It seems that someone put an item in a shop that the plugin doesnt like.
Any idea what it could be?
This is what i get on startup:
https://pastebin.com/kmCsDgNT

**Comment by Whazaaaaa** [comment] 2017-06-20 16:08
[shops.zip](https://github.com/Zerthick/PlayerShopsRPG/files/1088827/shops.zip)
If you're intrested in the shop file.

**Comment by Zerthick** [comment] 2017-06-20 22:51
Most likely something with custom data from another plugin.

**Comment by Whazaaaaa** [comment] 2017-06-21 05:13
How do I check/fix this?

**Comment by Zerthick** [comment] 2017-06-23 02:49
Working on it, I've determined is has to do with the items from the draconicevolution mod that are within some of your shops. I'm now trying to determine if this is due to an issue in my code, sponge itself, or the mod specifically.

**Comment by Zerthick** [comment] 2017-06-23 03:19
Ok, so it may not specifically be the draconicevolution mod that is the issue. What appears to be the issue is that at one point or another you had a mod installed and somebody put and item from that mod in their shop, but then you later removed that mod. So now what happens is when the plugin loads up it attempts to recreate that item, however since that item no longer exists it freaks out, make sense?

**Comment by Whazaaaaa** [comment] 2017-06-23 05:25
It sadly does not seeing as I've updated the pack a week before this issue came up. Meaning that I dont think I can be that as it didnt emediately happen after a modpack update.

**Comment by Zerthick** [comment] 2017-06-23 20:58
Hmmm, that leads me to believe that one of the mods in the pack isn't registering their items soon enough and this only now occurred because someone just added the item to their shop. If this is the case I can release a patch that will hopefully resolve the issue, however without a link to the modpack you are using I won't be able to test it.

**Comment by Whazaaaaa** [comment] 2017-06-23 20:59
This is what I currently use:
https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3/files/2418190

**Comment by Whazaaaaa** [comment] 2017-06-23 21:03
While you're maybe doing a hotfix someone found a very easy dupe bug
1) create a shop
2) add an Item to sell to the Shop
3)restock the shop with /shop item add while holding the item in your hand
4) it doesnt take the item out of your inve when you add it to the shop, so just buy it back from your Own shop for a price of 0 and bam,  you have double the items

**Comment by Zerthick** [comment] 2017-06-23 21:10
What version of Sponge?

**Comment by Whazaaaaa** [comment] 2017-06-23 21:11
spongeforge-1.10.2-2281-5.2.0-BETA-2379

**Comment by Zerthick** [comment] 2017-06-23 21:26
I have not be able to replicate this dupe on the latest stable version of SpongeForge `1.10.2-2281-5.2.0-BETA-2407` and PlayerShopsRPG [v2.0.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.0)

**Comment by Whazaaaaa** [comment] 2017-06-23 21:27
Ill restart my server and try it with the latest

**Comment by Whazaaaaa** [comment] 2017-06-23 21:37
Apparently I was misinformed. This dupe only happens on my AllTheMods2
https://minecraft.curseforge.com/projects/all-the-mods-2/files/2439222
with spongeforge: spongeforge-1.11.2-2315-6.1.0-BETA-2398
But seeing as this is a API 6 issue I guess there not much to be done besides a whole new version.

There was another dupe/infinite money one I've heard of. But the player that told me is currently online so Ill come back to that later.

**Comment by Whazaaaaa** [comment] 2017-06-23 22:06
Okay so this is a big dupe that still works.
1. Make shop
2. Add whatever item
3. do /shop item remove # -10 and it will add 10 items with no cost
So adding the minus f's up the system. I thought it already checked for a minus I thought I read in some changelog. But I guess not.
I tested this myself and it works :/
http://recordit.co/2FQlAK4GXW
That is a recording of me doing it just now if that helps.

**Comment by Zerthick** [comment] 2017-06-23 22:08
Please create a separate issue for it and I'll be sure to patch it asap.

I've determined it's the `withercrumbs:crumb_star` that appears to be causing the issue, I'm now trying to figure out why.

**Comment by Zerthick** [comment] 2017-06-23 22:20
Ok, it's as I expected, it registers it's items late, I'll have a patch out soon :smile:

**Comment by Zerthick** [comment] 2017-06-24 23:31
Should be fixed in [v2.0.1](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.1)!

**Closed by Zerthick** 2017-06-24 23:31 UTC
