### ISSUE TITLE
Enchanted books not working

### ISSUE THREAD

**Issue by aWitch-Doctor** [Zerthick/PlayerShopsRPG#19] opened 2017-04-20 10:50 UTC
Sponge vanilla api 5 latest version. and then a bunch of other plugins that i can get you a list of if you need it but i don't think you will.

If a player adds an enchanted book to the shop it works fine but then they try to add a different enchanted book and it wont let them. If they create a spot for silk 1 books they can add any enchanted book and it becomes silk 1. If they remove the books after they add them then they get all silk 1 books back instead of various enchants.

**Comment by aWitch-Doctor** [comment] 2017-04-21 13:34
This same thing happens with potions. They create regen potion in the shop then add any potion and it adds to the regen potion slot. After creating potion A they can't create potion B in the shop. Remove all potions from regen even after adding damage potions and they get all regen potions.

**Comment by Zerthick** [comment] 2017-04-21 22:37
I know what the issue is, just not sure how to fix it yet, working on it! 😃

**Comment by Zerthick** [comment] 2017-06-21 20:58
I have a patch in the works, expect a new release soon :smile:

**Comment by Zerthick** [comment] 2017-06-23 03:04
Should be fixed in [v2.0.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.0)!

**Closed** 2017-06-23 03:05 UTC
Labels: bug
