### ISSUE TITLE
Shop takes money but doesn't give item.

### ISSUE THREAD

**Issue by alphawolf918** [Zerthick/PlayerShopsRPG#31] opened 2017-07-29 01:08 UTC
Whenever I try to buy an item, it takes my currency (using latest version of Total Economy) from the database, but it tells me I don't have enough funds (after taking my money) and doesn't give me the item. Also when I try to deposit my funds into the shop's balance, it takes it but it says the balance is still 0. This is, like, illuminati stuff goin on here. I use Minecraft 1.11.2, Java 8.

**Comment by Zerthick** [comment] 2017-07-29 15:02
What version of PlayerShopRPG are you using?

**Comment by alphawolf918** [comment] 2017-07-29 15:53
The latest version. 2.0.3.

**Comment by Zerthick** [comment] 2017-08-08 22:42
That's weird I'll try to reproduce the issue.

**Comment by Zerthick** [comment] 2017-08-20 17:09
Does this still occur on the latest version [v2.0.5](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.5)?

**Comment by alphawolf918** [comment] 2017-11-25 00:00
Yes, it does. Sorry I took so long, I've had a lot going on.

When I try to deposit some of my own funds ($9,800) into the shop balance, it still says Shop Balance is set as $0.00, but my balance goes down to $9,700. Furthermore, the original issue has been slightly modified: now instead of taking my money when I buy an item, it tells me that I don't have enough funds (one piece of coal was set as $40 to buy and I have $9,700). The issue still persists.

Terribly sorry that it took me this long to get back to you. I also have updated to the latest SpongeForge for 1.11.2.

**Comment by alphawolf918** [comment] 2017-12-20 01:02
Any updates on this?

**Comment by Zerthick** [comment] 2017-12-20 23:00
Apologies, not yet, I also had a lot of stuff going on. I should be able to get to it this weekend though. Are you still using Minecraft 1.11.2 (Sponge API 6)?  The reason I ask is API 6 is going into maintenance mode at the end of the month and I'll be moving all my development to API 7 once that occurs.

**Comment by alphawolf918** [comment] 2017-12-21 03:05
Interesting, what does that mean exactly? Will my own plugin still work or does everything using API 6 catch fire? Anyway, yes, I'm still using 6. But if I'm forced to upgrade then I guess I won't have a choice but to use 7.

**Comment by Zerthick** [comment] 2017-12-21 17:02
If you remain on Minecraft 1.11.2 you will continue to use API 6 and all API 6 plugins should still work just fine.  If you want to move on to Minecraft 1.12.2 you will have to use API 7, basically each new major version of Minecraft gets a new API revision.  API revisions are usually breaking, meaning plugins written for one API version typically won't work on others.

**Comment by Zerthick** [comment] 2017-12-21 18:36
Using PlayerShopsRPG v2.0.5, TotalEconomy v1.7.1 and spongeforge-1.11.2-2476-6.1.0-BETA-2784 I am unable to replicate this issue. I tested depositing funds to a shop, the funds were withdrawn from my account and deposited into the shop's account, I also tested buying an item from a shop, again the funds were transferred correctly and the item was placed in my inventory.  Could you have some other economy plugin  installed that could be interfering with the transactions?

**Comment by alphawolf918** [comment] 2017-12-22 00:44
We're not, but it's okay. Decided on CarrotShop because it suits us better. But thank you for your time and effort. Appreciated it.

**Comment by Zerthick** [comment] 2017-12-22 19:41
I understand, and you're welcome!

**Closed by Zerthick** 2017-12-22 19:41 UTC
